# Generated by Django 5.0.6 on 2024-05-22 15:47

import helpdesk.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0040_alter_followup_new_status_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='email_on_ticket_change',
            field=models.BooleanField(default=helpdesk.models.email_on_ticket_change_default, help_text="If you're the ticket owner and the ticket is changed via the web by somebody else,do you want to receive an e-mail?", verbose_name='E-mail me on ticket change?'),
        ),
    ]
