version: '2'
services:
  demodesk:
    build: .
    volumes:
      - .:/app
    ports:
      - 8080:8080
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.5'
    #       memory: 256M
