version: '2'
services:
  postgres:
    image: postgres:12-bullseye
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    volumes:
      - ./db-dev:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - net
    restart: unless-stopped

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - net
    depends_on:
      - postgres
    restart: unless-stopped

networks:
  net:
    driver: bridge
