version: '2'
services:
  caddy:
    image: caddy:2
    restart: unless-stopped
    volumes:
      - /tmp/data/caddy/data:/data
      - /tmp/data/caddy/config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"
      - "443:443"
    networks:
    - net

  django-helpdesk:
    build:
      context: ..
      dockerfile: standalone/Dockerfile
    user: root
    volumes:
      - /tmp/django-helpdesk-data:/data/
      - ./custom_navigation_header.html:/opt/django-helpdesk/helpdesk/templates/helpdesk/custom_navigation_header.html
    env_file:
      - docker.env
    depends_on:
      - postgres
    networks:
      - net

  postgres:
    image: postgres:12-bullseye
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      - docker.env
    networks:
      - net

  adminer:
    image: adminer
    env_file:
      - docker.env
    ports:
      - 8080:8080
    networks:
      - net
    restart: unless-stopped

networks:
  net:
    driver: bridge
