version: '2'
services:
  nginx:
    build: ./nginx
    volumes:
      - ./static:/static
    ports:
      - 80:80
    networks:
      - net
    depends_on:
      - django-helpdesk
    restart: unless-stopped

  django-helpdesk:
    build:
      context: ..
      dockerfile: standalone/Dockerfile
    user: root
    volumes:
      - /tmp/django-helpdesk-data:/data/
      - ./custom_navigation_header.html:/opt/django-helpdesk/helpdesk/templates/helpdesk/custom_navigation_header.html
      - ./static:/static
    env_file:
      - docker.env
    depends_on:
      - postgres
    networks:
      - net

  postgres:
    image: postgres:12-bullseye
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      - docker.env
    networks:
      - net

  adminer:
    image: adminer
    env_file:
      - docker.env
    ports:
      - 8080:8080
    networks:
      - net
    restart: unless-stopped

networks:
  net:
    driver: bridge

volumes:
  static:
